<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Modules.Launches.IntegrationTests" />
    <InternalsVisibleTo Include="Modules.Orders.IntegrationTests" />
    <InternalsVisibleTo Include="Modules.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\FlashSales.Infrastructure\FlashSales.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Users\Modules.Users.Contracts\Modules.Users.Contracts.csproj" />
    <ProjectReference Include="..\Modules.Launches.Application\Modules.Launches.Application.csproj" />
    <ProjectReference Include="..\Modules.Launches.Contracts\Modules.Launches.Contracts.csproj" />
    <ProjectReference Include="..\Modules.Launches.Endpoints\Modules.Launches.Endpoints.csproj" />
  </ItemGroup>

</Project>
