// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Launches.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Launches.Infrastructure.Database.Migrations
{
    [DbContext(typeof(LaunchesDbContext))]
    partial class LaunchesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("launches")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlashSales.Application.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("JSONB");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<bool>("IsPermanentFailure")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.ToTable("InboxMessages", "launches");
                });

            modelBuilder.Entity("FlashSales.Application.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.HasKey("Id");

                    b.HasIndex("InboxMessageId", "Name")
                        .IsUnique();

                    b.ToTable("InboxMessageConsumers", "launches");
                });

            modelBuilder.Entity("FlashSales.Application.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("JSONB");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<bool>("IsPermanentFailure")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.ToTable("OutboxMessages", "launches");
                });

            modelBuilder.Entity("FlashSales.Application.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OutboxMessageId", "Name")
                        .IsUnique();

                    b.ToTable("OutboxMessageConsumers", "launches");
                });

            modelBuilder.Entity("Modules.Launches.Domain.Launches.Entities.Launch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SellerId", "Status");

                    b.ToTable("Launches", "launches");
                });

            modelBuilder.Entity("Modules.Launches.Domain.Launches.Entities.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LaunchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LaunchId", "OrderId")
                        .IsUnique();

                    b.ToTable("StockReservations", "launches");
                });

            modelBuilder.Entity("Modules.Launches.Domain.Sellers.Entities.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Sellers_UserId");

                    b.ToTable("Sellers", "launches");
                });

            modelBuilder.Entity("FlashSales.Application.Inbox.InboxMessageConsumer", b =>
                {
                    b.HasOne("FlashSales.Application.Inbox.InboxMessage", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashSales.Application.Outbox.OutboxMessageConsumer", b =>
                {
                    b.HasOne("FlashSales.Application.Outbox.OutboxMessage", null)
                        .WithMany()
                        .HasForeignKey("OutboxMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Launches.Domain.Launches.Entities.Launch", b =>
                {
                    b.OwnsOne("Modules.Launches.Domain.Launches.ValueObjects.LaunchMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("LaunchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("VARCHAR(2000)")
                                .HasColumnName("Description");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("VARCHAR(200)")
                                .HasColumnName("Title");

                            b1.HasKey("LaunchId");

                            b1.ToTable("Launches", "launches");

                            b1.WithOwner()
                                .HasForeignKey("LaunchId");
                        });

                    b.OwnsOne("Modules.Launches.Domain.Launches.ValueObjects.LaunchPrice", "Price", b1 =>
                        {
                            b1.Property<Guid>("LaunchId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("DiscountedPrice")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("DiscountedPrice");

                            b1.Property<decimal>("OriginalPrice")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("OriginalPrice");

                            b1.HasKey("LaunchId");

                            b1.ToTable("Launches", "launches");

                            b1.WithOwner()
                                .HasForeignKey("LaunchId");
                        });

                    b.OwnsOne("Modules.Launches.Domain.Launches.ValueObjects.LaunchSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("LaunchId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("EndAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndAt");

                            b1.Property<DateTimeOffset>("StartAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartAt");

                            b1.HasKey("LaunchId");

                            b1.ToTable("Launches", "launches");

                            b1.WithOwner()
                                .HasForeignKey("LaunchId");
                        });

                    b.OwnsOne("Modules.Launches.Domain.Launches.ValueObjects.LaunchStock", "Stock", b1 =>
                        {
                            b1.Property<Guid>("LaunchId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ReservedQuantity")
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("ReservedQuantity");

                            b1.Property<int>("TotalQuantity")
                                .HasColumnType("integer")
                                .HasColumnName("TotalQuantity");

                            b1.HasKey("LaunchId");

                            b1.ToTable("Launches", "launches");

                            b1.WithOwner()
                                .HasForeignKey("LaunchId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Price");

                    b.Navigation("Schedule");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Modules.Launches.Domain.Launches.Entities.StockReservation", b =>
                {
                    b.HasOne("Modules.Launches.Domain.Launches.Entities.Launch", null)
                        .WithMany("StockReservations")
                        .HasForeignKey("LaunchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Launches.Domain.Launches.Entities.Launch", b =>
                {
                    b.Navigation("StockReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
