// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Coupons.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Coupons.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CouponsDbContext))]
    partial class CouponsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("coupons")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlashSales.Application.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("JSONB");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<bool>("IsPermanentFailure")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.ToTable("InboxMessages", "coupons");
                });

            modelBuilder.Entity("FlashSales.Application.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.HasKey("Id");

                    b.HasIndex("InboxMessageId", "Name")
                        .IsUnique();

                    b.ToTable("InboxMessageConsumers", "coupons");
                });

            modelBuilder.Entity("FlashSales.Application.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("JSONB");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<bool>("IsPermanentFailure")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.ToTable("OutboxMessages", "coupons");
                });

            modelBuilder.Entity("FlashSales.Application.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OutboxMessageId", "Name")
                        .IsUnique();

                    b.ToTable("OutboxMessageConsumers", "coupons");
                });

            modelBuilder.Entity("FlashSales.Infrastructure.Authorization.RolePermission", b =>
                {
                    b.Property<string>("RoleName")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("RoleName", "PermissionCode");

                    b.ToTable("RolePermissions", "coupons");
                });

            modelBuilder.Entity("FlashSales.Infrastructure.Authorization.UserRole", b =>
                {
                    b.Property<string>("IdentityProviderId")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("RoleName")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("IdentityProviderId", "RoleName");

                    b.ToTable("UserRoles", "coupons");
                });

            modelBuilder.Entity("Modules.Coupons.Domain.Coupons.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LaunchId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxRedemptionsPerCustomer")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons", "coupons");
                });

            modelBuilder.Entity("Modules.Coupons.Domain.Coupons.Entities.CouponRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.ToTable("CouponRedemption", "coupons");
                });

            modelBuilder.Entity("FlashSales.Application.Inbox.InboxMessageConsumer", b =>
                {
                    b.HasOne("FlashSales.Application.Inbox.InboxMessage", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashSales.Application.Outbox.OutboxMessageConsumer", b =>
                {
                    b.HasOne("FlashSales.Application.Outbox.OutboxMessage", null)
                        .WithMany()
                        .HasForeignKey("OutboxMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Coupons.Domain.Coupons.Entities.Coupon", b =>
                {
                    b.OwnsOne("Modules.Coupons.Domain.Coupons.ValueObjects.CouponDiscount", "Discount", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("MaxDiscountAmount")
                                .HasColumnType("DECIMAL(18,2)")
                                .HasColumnName("MaxDiscountAmount");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("VARCHAR(20)")
                                .HasColumnName("Type");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL(18,2)")
                                .HasColumnName("Value");

                            b1.HasKey("CouponId");

                            b1.ToTable("Coupons", "coupons");

                            b1.WithOwner()
                                .HasForeignKey("CouponId");
                        });

                    b.OwnsOne("Modules.Coupons.Domain.Coupons.ValueObjects.CouponUsage", "Usage", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxRedemptions")
                                .HasColumnType("INT")
                                .HasColumnName("MaxRedemptions");

                            b1.Property<int>("RedeemedCount")
                                .HasColumnType("INT")
                                .HasColumnName("RedeemedCount");

                            b1.HasKey("CouponId");

                            b1.ToTable("Coupons", "coupons");

                            b1.WithOwner()
                                .HasForeignKey("CouponId");
                        });

                    b.OwnsOne("Modules.Coupons.Domain.Coupons.ValueObjects.CouponValidity", "Validity", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("ValidFrom")
                                .HasColumnType("DATETIME")
                                .HasColumnName("ValidFrom");

                            b1.Property<DateTimeOffset>("ValidUntil")
                                .HasColumnType("DATETIME")
                                .HasColumnName("ValidUntil");

                            b1.HasKey("CouponId");

                            b1.ToTable("Coupons", "coupons");

                            b1.WithOwner()
                                .HasForeignKey("CouponId");
                        });

                    b.Navigation("Discount")
                        .IsRequired();

                    b.Navigation("Usage")
                        .IsRequired();

                    b.Navigation("Validity")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Coupons.Domain.Coupons.Entities.CouponRedemption", b =>
                {
                    b.HasOne("Modules.Coupons.Domain.Coupons.Entities.Coupon", null)
                        .WithMany("Redemptions")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Coupons.Domain.Coupons.Entities.Coupon", b =>
                {
                    b.Navigation("Redemptions");
                });
#pragma warning restore 612, 618
        }
    }
}
